<a href="https://colab.research.google.com/github/MorshedulHoque/Pytorch/blob/main/Tensors_in_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.5.1+cu124


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
else:
  print("GPU not available")

GPU not available


# **Creating tensor**

In [ ]:
a= torch.empty(2,3)

In [ ]:
type(a)

torch.Tensor

In [ ]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(2,3)

tensor([[0.4210, 0.7588, 0.5121],
        [0.4696, 0.5376, 0.7807]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

Tensor shapes

In [ ]:
x = torch.tensor([[1,2,4],[5,6,7]])
x

tensor([[1, 2, 4],
        [5, 6, 7]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[    139946542046608,     139946542046608,                   0],
        [                  0,                   0, 7310593858020254331]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

# **Tensor data type**

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1,2,3], dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
x.to(torch.float64)

tensor([[1., 2., 4.],
        [5., 6., 7.]], dtype=torch.float64)

# **Mathematical operations**

# 1. Scalar operation

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.2627, 0.0428],
        [0.2080, 0.1180]])

In [ ]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.0690, 0.0018],
        [0.0433, 0.0139]])

# 2. Element wise operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.1217, 0.7356, 0.7118],
        [0.7876, 0.4183, 0.9014]])
tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])


In [ ]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.1217, 0.7356, 0.0401],
        [0.1829, 0.0615, 0.0776]])

In [ ]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

# 3. Reduction operation

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[4., 6., 0.],
        [1., 9., 9.]])

In [ ]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([10., 19.])

In [ ]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([2.5000, 7.5000, 4.5000])

In [ ]:
# median
torch.median(e)

tensor(4.)

In [ ]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

# 4. Matrix operations

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[8, 0, 7],
        [0, 0, 9]])
tensor([[5, 7],
        [3, 9],
        [4, 0]])


In [ ]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[68, 56],
        [36,  0]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# transpose
torch.transpose(f, 0, 1)

tensor([[8, 0],
        [0, 0],
        [7, 9]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 7., 5.],
        [9., 9., 7.],
        [5., 9., 8.]])

# 5. Comparison operations

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[9, 7, 9],
        [2, 6, 7]])
tensor([[7, 8, 3],
        [6, 1, 5]])


In [ ]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

# 6. Special functions

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[5., 0., 4.],
        [3., 8., 8.]])

In [ ]:
# log
torch.log(k)

tensor([[1.6094,   -inf, 1.3863],
        [1.0986, 2.0794, 2.0794]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[2.2361, 0.0000, 2.0000],
        [1.7321, 2.8284, 2.8284]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.5000, 0.9820],
        [0.9526, 0.9997, 0.9997]])

In [ ]:
# softmax
torch.softmax(k, dim=0)

tensor([[8.8080e-01, 3.3535e-04, 1.7986e-02],
        [1.1920e-01, 9.9966e-01, 9.8201e-01]])

In [ ]:
# relu
torch.relu(k)

tensor([[5., 0., 4.],
        [3., 8., 8.]])

# **Inplace Operations**

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6179, 0.3379, 0.2170],
        [0.9454, 0.7116, 0.1157]])
tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])


In [ ]:
m.add_(n)

tensor([[1.2752, 0.6830, 0.2624],
        [1.9251, 1.2663, 0.8025]])